### ISSUE TITLE
How to select year !? How to type date !? 

### ISSUE THREAD

**Issue by RezaPouya** [dyonir/vue2-persian-datepicker#16]
how can I select year !? 
and how can I type date in selected format directly !? 

//===========
update : 

thanks , I developing a website for a company and they have to use large screen , mouse and keyboard for their display and input devices , so having formated input will ease their users .... 

and what about selecting year !? 

I want to use this DatePicker for  BirthDate and right now , I have to click more than 40 times to set year of customer's birth date to something like 1356 and this is nightmare !!!

I just decide to use Vue for this project in day before yesterday and I'm relativity new in this field ,, but If I had time to work more with Vue and find any solution for these problems , I would share it with you ... 

thanks for your effort ...

**Comment by rhajizadeh** [comment]
For responsive reasons I disabled the input so you cannot type date into input textbox.
The problem was that the dialog will be covered by android or ios virtual keyboard. So if you have an idea that could solve this issue tell me and I will implement it.
For selecting years you can go to months and then change the year by moving forward or backward in years.

**Comment by rhajizadeh** [comment]
Non the less I will add an option too override this property.So you can enable the textbox if you need to.

**Comment by rhajizadeh** [comment]
please open an another issue for selecting year
